INSERT OR IGNORE INTO Requirements (RequirementId, RequirementType) VALUES
	('REQUIRES_PLOT_HAS_ANY_IMPROVEMENT', 'REQUIREMENT_PLOT_HAS_ANY_IMPROVEMENT');

INSERT OR IGNORE INTO RequirementSets (RequirementSetId, RequirementSetType)
	VALUES ('PLOT_HAS_ANY_FEATURE', 'REQUIREMENTSET_TEST_ALL');
INSERT OR IGNORE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
	VALUES ('PLOT_HAS_ANY_FEATURE', 'PLOT_HAS_ANY_FEATURE_REQUIREMENT');

INSERT OR IGNORE INTO Types (Type, Kind) VALUES ('MODIFIER_SINGLE_CITY_TRAINED_UNITS_ADJUST_MOVEMENT', 'KIND_MODIFIER');
INSERT OR IGNORE INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES
	('MODIFIER_SINGLE_CITY_TRAINED_UNITS_ADJUST_MOVEMENT', 'COLLECTION_CITY_TRAINED_UNITS', 'EFFECT_ADJUST_UNIT_MOVEMENT');

INSERT OR IGNORE INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
	('DISTRICT_IS_CITY_CENTER', 'REQUIREMENTSET_TEST_ALL');
INSERT OR IGNORE INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
	('DISTRICT_IS_CITY_CENTER', 'REQUIRES_DISTRICT_IS_CITY_CENTER');

INSERT OR IGNORE INTO CivicModifiers (CivicType, ModifierId) VALUES
	('CIVIC_THE_ENLIGHTENMENT', 'CIVIC_GRANT_PLAYER_GOVERNOR_POINTS'),
	('CIVIC_MERCANTILISM', 'CIVIC_GRANT_PLAYER_GOVERNOR_POINTS');

UPDATE ModifierArguments SET Value=2 WHERE ModifierId='CONTRATACION_GOVERNOR_POINTS' AND Name='Delta';
